name: Generate Chat SVG

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-chat-svg
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create chat SVG
        run: |
          mkdir -p chat
          cat << 'EOF' > chat/chat.svg
<svg width="550" height="684" viewBox="0 0 550 684" fill="none" xmlns="http://www.w3.org/2000/svg">
  <style>
    .bubble { fill: #e9e9eb; }
    text { fill: #242424; font-size: 18px; font-family: 'Inter'; }
  </style>

  <!-- Messages -->
  <g transform="t
